#index:
#    path: /
#    controller: App\Controller\DefaultController::index

bye_bye_ world:
    path: /byebye-world
    controller: App\Controller\ByeController::index

#oc_advert_index:
#    path:       /advert
#    controller: App\Controller\AdvertController::index

#oc_advert_view:
#    path:       /advert/view/{id}
#    controller: App\Controller\AdvertController::view

#oc_advert_add:
#    path:       /advert/add
#    controller: App\Controller\AdvertController::add
